import { Component } from 'react';
import '../assets/style/components/Features.scss';
import searchIcon from '../assets/images/features/search.svg';
import selectIcon from '../assets/images/features/select.svg';
import standOutIcon from '../assets/images/features/stand-out.svg';
class Features extends Component {
    render() {
        return (
            <section className="features">
                <div className="container">
                    <div className="features_list">
                        <div className="features_list-item">
                            <img src={searchIcon} alt="Search"/>
                            <h5 className="title">
                                Search
                            </h5>
                            <p className="text">
                                Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.
                            </p>
                        </div>
                        <div className="features_list-item">
                            <img src={selectIcon} alt="Select"/>
                            <h5 className="title">
                                Select
                            </h5>
                            <p className="text">
                                Choose from thousands of options generated by the slogan maker that fit your needs.
                            </p>
                        </div>
                        <div className="features_list-item">
                            <img src={standOutIcon} alt="Stand Out"/>
                            <h5 className="title">
                                Stand Out
                            </h5>
                            <p className="text">
                                Congrats on your new slogan. It's time to win the world!
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        )
    }
}
export default Features;